_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "/opt/tiger/Beta_SPose_last/swin/swin_base_patch4_window7_224_22k.pth"
  BACKBONE:
    NAME: "build_swin_fpn_backbone"
  SWINS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    type: 'swinT'
  SparseRCNN:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("keypoints_coco_2017_train",)
  TEST:  ("keypoints_coco_2017_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
